# Generated by Django 5.0.1 on 2024-03-03 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries_ssu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='employer_type',
            field=models.CharField(choices=[('GOB', 'GOB'), ('NIT', 'NIT'), ('RUC', 'RUC'), ('SUP', 'SUP')], default='NIT', max_length=3, verbose_name='tipo de empleador'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='gender',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], default='M', max_length=1, verbose_name='género'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Soltero(a)'), ('C', 'Casado(a)'), ('V', 'Viudo(a)'), ('D', 'Divorciado(a)')], default='S', max_length=1, verbose_name='estado civil'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaries_ssu.institution'),
        ),
    ]
